=head0 THE PREPARATION (the Last Six Months)

Once you've got yourself underway, many of the early tasks will either be in 
full flow by now, or finished. It's now time to think about the promotional side 
of things and invite people to be involved in your conference.

L<timeline3>

=head1 PLANNING MEETINGS

By now the team should be fairly familiar with the tasks ahead of them. You only 
have six months left and it will pass very quickly. From this point forward it 
is important to continue with regular face to face planning meetings. These 
should increase in frequency as you get closer to the event.

=head2 Update You Project Plan

The tasks you outlined for completion in the last six months before your event, 
should now all have start and end dates. There will likely be some additional 
tasks and dates that you need to add based on previous tasks.

L<budget_progress>

L<volunteers>

L<speakers_invite>

L<website_launch>

L<promotion>

L<announcements>

L<call_for_papers>

L<call_for_registration>

L<conference_schedule>

L<conference_pack>

L<deadlines>

L<conference_events>

L<conference_accessories>
