=head0 Preface

This book is split into several chapters, each focusing on a specific
aspect of organising a conference, together a little bit of background and
history at the end for those wishing to understand how the early YAPC experience
developed into the events they are now.

L<structure>

=head1 Comments and Questions

Please address comments and questions concerning this book to the author:

  Barbie
  barbie@missbarbell.co.uk

If you find any errors in the book, or have any suggestions for improvements, 
you can contribute changes to the content of the book, either by contacting the 
author directly (as above) or via the public git repository and send patches or 
pull requests.

  https://github.com/barbie/perl-jam

L<acknowledgements>

=head1 Dedication

I couldn't have written this book without the love and encouragement of my wife 
and family, Nicole, Dan & Ethne. They have lost me for many weeks over the years
while attending various conferences and workshops, as well as all the time spent 
co-organising the 2006 YAPC::Europe Perl Conference and two QA Hackathon (2009
& 2016). Thank you.
