=head1 THE FIRST 12 YEARS

=head2 1999 - How It All Began

Z<first_11_years> The first Yet Another Perl Conference was held in Pittsburgh, PA at Carnegie 
Mellon University in 1999, and had about 275 participants. The event was 
attended by a small but mighty group of interested and interesting Perl people, 
including Larry Wall, who delivered the opening keynote on the first day of the 
two-day event.

=head2 2000 - The Art Spreads

The event was such a success that it was repeated, again at Carnegie Mellon 
University, in 2000 and was dubbed YAPC North America 19100, in honour of all 
the "Y2K" concerns of the time.  Attendance was some three hundred and fifty 
people.

Inspired by the success of the North American event, LE<eacute>on Brocard, Greg 
McCarroll and Jonathan Peterson took it upon themselves to organise the first 
European YAPC in 2000, at the Institute for Contemporary Arts (ICA) in London, 
with the theme "The Art of Perl."  Some two hundred people attended, with many 
volunteers from London.pm and surrounding areas helping out.

=head2 2001 - Security

In 2001, YAPC North America left Pittsburgh for Montreal, where Richard Lafferty 
and Luc St-Louis chaired the conference at the University of Montreal. About 
four hundred and twenty people attended. Once again, local groups turned out in 
numbers to volunteer for any and all tasks.

The European YAPC went into another strong year with YAPC::Europe 2001 at 
Hogeschool Holland, Amsterdam, with a Security theme.  Ann Barcomb, Jouke 
Visser, together with a large and dedicated crew from the Netherlands, created 
an excellent atmosphere for both talks and discussion, raising the overall 
standard once again.

=head2 2002 - Science

In 2002, YAPC::NA headed back below the border to Saint Louis, Missouri.

YAPC::Europe was hosted by Munich.pm, the week before Oktoberfest, at Technische 
UniversitE<auml>t ME<uuml>nchen, with a theme of "The Science of Perl". Norbert 
GrE<uuml>ner and crew enticed Larry Wall, Damian Conway and Michael Schwern to 
attend, ending the auction with Damian and Schwern featuring in a bare-chested 
arm-wrestling match!

=head2 2003 - The One With The Two YAPC::NAs

In 2003, YAPC::NA had two vying parties, the first was alternatively titled 
YAPC::Canada and held in Ottawa, Ontario, while the second was held in Boca 
Raton, Florida.

YAPC::Europe was hosted by Paris.pm at the Conservatoire National des Arts et 
ME<eacute>tiers (CNAM) in Paris. David Landgren, Philippe 'BooK' Bruhat and crew 
held a very vibrant conference with Mark Jason Dominus managing to hold court in 
the main room for all of day one.

=head2 2004 - Fun And Profit

Heading back towards the northern states, the 2004 YAPC::NA was held in Buffalo, 
New York. Jim Brandt and team hosted the event at the University at Buffalo and 
introduced a 'Poster BOF'!

YAPC::Europe was hosted by Belfast.pm in Northern Ireland, UK. As with London 
before them, they broke away from the education establishments and hosted the 
event in a converted church, now know as Squires.

=head2 2005 - Perl Everywhere

For 2005, YAPC::NA again headed north of the border and was successfully hosted 
by Toronto.pm. The Conference Dinner and Auction was held aboard a paddle 
steamer, that allowed attendees to relax for an evening and enjoy the Toronto 
skyline from the water.

YAPC::Europe was hosted by Braga.pm in northern Portugal, at University of 
Minho, Braga. JosE<eacute> Castro and Alberto Simoes worked hard to create a 
great conference. They included the first all attendees Conference Dinner for a 
YAPC::Europe conference, which also featured the unusual Beers Of The World BOF.

=head2 2006 - Accessible Perl

For 2006, YAPC::NA was hosted by Chicago.pm, and organised with great success by 
Josh McAdams and Pete Krawczyk. The Conference Dinner and Auction were held in a 
games arcade. The auction for this year introduced, quite successfully, a silent 
auction. This meant all the regular auction items (mostly books), could be 
auctioned off quickly and left plenty of time for the fun stuff.

YAPC::Europe was hosted by Birmingham.pm once again in the UK, at a concert 
venue, The CBSO Centre, with a theme of "The Accessibility of Perl". Barbie, Jon 
Allen, Steve Pitchford and Brian McCauley, together with their onsite crew 
helped to create yet another successful event, introducing an expo feature to 
the European conferences similar to the Chicago event. The event was notable for 
the fact it was publicly 3 years in the making, and featured a movie, "The 
Birmingham Job" as part of the bid submission to host the event. Final role call 
was 228 attendees.

Interesting aside: Chicago and Birmingham are also twinned-cities.

=head2 2007 - Social Perl

In 2007, YAPC::NA headed the furthest west it had ever been, with Houston.pm 
hosting the YAPC::NA 2007. Despite the humidity tiring everyone out, the 
conference was very well received and the games arcade seem to go down VERY well 
:)

In Europe, YAPC::Europe headed to Austria, as hosted by Vienna.pm. Vienna is a 
city full of sights to see, and the conference itself managed to attract some 
illuminating speakers too, including Larry, Damian and Mark-Jason Dominus. The 
event also introduced the idea of full day workshops and hackathons, with 
Parrot, Perl 6 and POE all getting their own dedicated hacker rooms.

=head2 2008 - Beautiful Perl

After taking on the conference for 2006, Chicago once again hosted YAPC::NA 
2008. As for 2006, the breakfast buffet (as well morning and afternoon breaks) 
were a wonderful addition to keep everyone going throughout the day.

YAPC::Europe was Scandinavian bound, with the event being hosted by 
Copenhagen.pm. The lunch bags went down very well, which was just as well as the 
city was rather expensive for many this year.

=head2 2009 - Corporate Perl

Celebrating ten years, although it was the 11th YAPC, YAPC::NA returned to 
Pittsburgh and Carnegie Mellon University, now holding the honour of host the 
event 3 times.

YAPC::Europe went to Portugal again for 2009, and although it was located in 
Lisbon this time around, the familiar organisers of Jose, Alberto and Joana were 
behind it all. The event featured a host of talks and tutorials, and was the 
first to have a successful Partner Programme.

=head2 2011 - Modern Perl

YAPC::Europe moved to the most Eastern city every, to Riga in Latvia. The
conference was organized fully remotely by the members of Moscow.pm living in
Amsterdam (Andrew Shitov), Moscow (Alex Kapranov) and Copenhagen (Dmitry Karasik).
278 people, incuding Larry Wall and Damian Conway, attended the conference.
A few steps were made to move all the conference materials and activities
previously lived on paper to the internet. The crew hired aditional stuff to work
on Wi-Fi and food in the venue.
