=head1 THE CONFERENCE SURVEYS

Z<surveys> The Conference Surveys website started in 2006, and are now a regular
feature of both The Perl Conference in Europe and The Perl Conference in North
America. If you wish to provide a survey at your event, you can contact
surveys@yapc-surveys.org and request for an instance to be set-up. There are two
forms of surveys available, the talk evaluations and the main conference survey.

The talk evaluations are purely for the benefit of the speakers. Results of 
these evaluations are not made public, unless the speaker themselves publishes 
them. They open after each talk takes place and are open until the closing date 
of the main conference survey.

The main conference survey opens at the end of the conference and is typically 
open for about 2 weeks. The survey results are collated and published on The 
Conference Surveys website, which can then be used by future organisers to 
help attract sponsors and generally improve the conference experience for 
everyone.

It is worth reading previous surveys, as they can provide facts and figures that 
can help encourage sponsors.

