=head1 TIMELINE 4 - THE EVENT

Z<timeline4> While not strictly a timeline, the following are all items you'll
need to schedule and prepare for during the event, and make attendees aware of 
throughout the event too.

=over

=item * Partner Programmes

=item * Early Arrivals Meetup

=item * Pre-registration

=item * Registration

=item * Opening Address

=item * Keynotes

=item * Talks

=item * Birds of a Feather sessions (BOFs)

=item * Tutorials & Workshops

=item * Evening Events

=item * Conference Dinner

=item * Next Year's Conference

=item * Closing Address

=back

