=head1 TIMELINE 2 - THE FOUNDATIONS

Z<timeline2>

Below are the main events in the first phase of the actual conference 
preparation life-cycle. As before, refer to this as you prepare for the 
conference to make sure you are on track and haven't missed anything.

=over

=item * Plan Your Project

Outline tasks and priorities.

=item * Establish Your Team

You'll need one!

=item * Book the Venue

Sign the contract and pay the deposit.

=item * Announce the Dates

If you can announce dates as early as possible, but not before booking the 
venue.

=item * Design Your Website

Start working on your website, its the key promotional aid for yout event.

=item * Find Sponsors

Start approaching previous sponsors and any new big sponsors.

=back

These are tasks which usually begin about a year in advance of your event. It is 
important all these get started early, as these are the foundations of the work 
you will be concentrating on for the six months prior to your event. 

