=head1 CONFERENCE TIMELINE (PART 1) - THE BID

Z<timeline1>

Below are the main events in the conference bid life-cycle. Refer to this as 
you prepare your bid to keep yourself on track. The sections in this chapter 
explain more fully the details of each step.

Ensure you time the end dates for any submissions, presentations and 
announcements carefully, so you are not rushing to complete them.

=over

=item * Prepare Your Team

You shouldn't try this on your own, try and get a team together.

=item * Research Your Venue

Possibly the most important part of your bid to get right.

=item * Prepare Your Bid

Start your planning early, read other bids.

=item * Call for Venue

Official announcement. Read it carefully and note the deadline.

=item * Submit Your Bid

Ensure you submit before the deadline to the correct address.

=item * Committee Questions

Be prepared for questions.

=item * Official Announcements

What happens after the winner is decided.

=back

