=head1 BOOK THE VENUE

Z<venue_booking>

Ideally you should book your venue as soon as you have won the bid, but you will 
need to sign some form of contract at least 6 months (preferably sooner) prior 
to the start of the conference. Confirm dates with the venue and provide a 
booking deposit, if you can, to secure the venue on the dates you require. Some 
venues may be happy to hold the dates for you and wait for you to pay the 
deposit a few months prior to the conference.

However, paying a deposit can be extremely difficult to do if you start with no 
funds. Thankfully help is usually at hand. Previous organisers, TPF/YEF and 
may be able to provide a kick start donation. This isn't likely to be much, but 
it should be enough to put down a deposit. If this is not possible you may need 
to look for some sponsorship ahead of time to ensure you can cover this and any 
other deposits.

Most venues will expect some form of deposit with the full amount settled in 
installments or paid full by a set date. Thankfully, some venues are very 
accommodating and will allow you to settle after the event. Whichever way you 
need to pay, do not miss any payments. Remember the venue is the key ingredient 
to the event, without it, you don't have an event. Paying on time, and keeping 
good relationships with the venue staff has other benefits. If the venue staff 
have a very positive experience with you, during the event you can find they are 
very accommodating with any unforeseen requests. If they have found you 
difficult to deal with, they are less likely to agree to helping you should you 
need it.

