=head1 RECRUITING VOLUNTEERS

Z<volunteers> In the six months before your event you will have many small tasks that can be 
completed by someone outside of your core team. Recruit a local crew who are 
willing help with fetching and carrying, and will act as volunteers and 
timekeepers during the event too. 

These people will not necessarily have a lot of free time before the conference, 
but they can help with some research, pick-up and drop-off items or generally 
look after things that don't necessarily have an urgent deadline, but that you 
still need to get done.

Some of the best volunteers during the event are often those who have no 
interest in the subject, and may not even have any technology background. Some 
education establishments (regardless of whether one is your venue) have student 
teams to acts as timekeepers and runners. You may need to pay them, but this can 
often be worthwhile.

You may also want to ask the community whether anyone would like to help out. 
Offer free entrance (or reduced entrance if your budget is tight) for anyone 
willing to help. You will likely find several people offering to help out for a half a 
day, a full day and maybe even the for the full conference.

